export const AppIcons = {
  focusHomeTab: require('../icons/focusHomeIcon.png'),
  homeTab: require('../icons/homeIcon.png'),
  focusChatTab: require('../icons/focusChatIcon.png'),
  chatTab: require('../icons/chatIcon.png'),
  focusListTab: require('../icons/focusListIcon.png'),
  listTab: require('../icons/listIcon.png'),
  focusProfileTab: require('../icons/focusProfileIcon.png'),
  profileTab: require('../icons/profileIcon.png'),
  forwardIcon: require('../icons/forwardIcon.png'),
  editIcon: require('../icons/edit.png'),
  feedBackIcon: require('../icons/feedback.png'),
  privacyIcon: require('../icons/privacy.png'),
  servicesIcon: require('../icons/terms.png'),
  refralIcon: require('../icons/invite.png'),
  profileIcon: require('../icons/profileIcon.png'),
  logoutIcon: require('../icons/logout.png'),
  backIcon: require('../icons/backIcon.png'),
};
